name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application JAR
      working-directory: ./22_DockerizingOurApp/rest-with-spring-boot-and-java-erudio
      run: mvn clean package -DskipTests

    - name: Docker Compose Build
      working-directory: ./22_DockerizingOurApp
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: | 
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:latest gabrielsmm/rest-with-spring-boot-erudio:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:latest
